apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tef15w9ww-python 
  janus-idp.io/tekton: tef15w9ww-python
  backstage.io/kubernetes-id: tef15w9ww-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tef15w9ww-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  