apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tef15w9ww-python-gitops
  description: This is GitOps manifest for tef15w9ww-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: tef15w9ww-python
    backstage.io/kubernetes-id: tef15w9ww-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: tef15w9ww-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:tef15w9ww-python
