apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tef15w9ww-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tef15w9ww-python 
  name: tef15w9ww-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tef15w9ww-python 
